root_data: '../../../data/'
root0: '../../../data/covid/'
root_data_aux: '../../../data_aux/'

project: 'Taubate COVID-19'
s_project: 'taubate_covid19'

email: <my_email>.com

gene_protein: 'protein'
s_omics: 'proteomics'

has_age: True
has_gender: True

want_normalized: False

abs_lfc_cutoff_inf: 0.40
s_pathw_enrichm_method: 'enricher'
num_min_degs_for_ptw_enr: 3

tolerance_pathway_index: 0.15
type_sat_ptw_index: 'linear_sat'
saturation_lfc_index: 5

pval_pathway_cutoff: 0.05
fdr_pathway_cutoff: .05
num_of_genes_cutoff: 3

case_list: ['g2a_male', 'g2a_female', 
            'g2b_male', 'g2b_female', 
            'g3_male_adult',   'g3_male_elder',
            'g3_female_adult', 'g3_female_elder']

case_sel_list: ['g3_male_adult', 'g3_female_elder']
s_len_case: 15

#--------- Gemini -----------

API_KEY: <my_gemini_key>
disease: 'COVID-19'
context_disease: "COVID-19 is the disease caused by the virus SARS-CoV-2. When the virus enters your body, it infects cells, primarily in the respiratory system."

n_sentences: 5
run_list: ['run01', 'run02']
chosen_model_list: [1, 3]
i_dfp_list: [0, 1, 2, 3]
chosen_model_sampling: 3

terms1_param: ["OR", 'COVID', 'SARS-CoV-2']
terms2_param: []
terms_not_param: ['NOT', 'MERS', 'SARS-CoV-1']
connective_param: 'AND'

# CAP: community-acquired pneumonia
# MV: mechanical ventilator
remove_synonym_list:  ['CAP', 'MV', 'MDB']
inidate: "2019/10/01"
enddate: "2030/12/31"

verbose_query: False
force_query: False

sleep_entrez: [5, 7, 10]
retmax: 100000

try_all_text: True
text_quote: ''
dec_ncpus: 2

sleep_TIKA: [10, 20, 30]
min_words_text: 100





