root_data: '../../../data/'
root0: '../../../data/mb/'
root_data_aux: '../../../data_aux/'

project: 'Medulloblastoma microarray study'
s_project: 'medulloblastoma'

email: <my_email>.com

gene_protein: 'dna'
s_omics: 'microarray'

has_age: False
has_gender: False

want_normalized: False

abs_lfc_cutoff_inf: 0.80
s_pathw_enrichm_method: 'enricher'
num_min_degs_for_ptw_enr: 3

tolerance_pathway_index: 0.15
type_sat_ptw_index: 'linear_sat'
saturation_lfc_index: 5

pval_pathway_cutoff: 0.05
fdr_pathway_cutoff: .05
num_of_genes_cutoff: 3

case_list: ['WNT', 'G4']
case_sel_list: ['WNT', 'G4']
s_len_case: 3

#--------- Gemini -----------

API_KEY: <my_gemini_key>
disease: 'medulloblastoma'
context_disease: "Medulloblastoma is a rare and aggressive type of brain tumor that primarily affects children and young adults. It originates in the cerebellum, the part of the brain responsible for coordination, balance, and motor skills."

n_sentences: 5
run_list: ['run01', 'run02', 'run03']
i_dfp_list: [0, 1, 2, 3]
chosen_model_list: [1,3]
chosen_model_sampling: 3

terms1_param: ["OR", 'medulloblastoma', 'MB']
terms2_param: []
terms_not_param: ['NOT', 'COVID', 'SARS-CoV']
connective_param: 'AND'

# CAP: community-acquired pneumonia
# MV: mechanical ventilator
remove_synonym_list:  ['CAP', 'MV', 'MDB']
inidate: "1990/01/01"
enddate: "2030/12/31"

verbose_query: False
force_query  : False

sleep_entrez: [5, 7, 10]
retmax: 100000

try_all_text: True
text_quote: ''
dec_ncpus: 2

sleep_TIKA: [10, 20, 30]
min_words_text: 100





